trigger:
  branches:
    include:
      - damiao-1.0

pool:
  vmImage: 'ubuntu-latest'

steps:

# 1. Instalar Flutter
- script: |
    git clone https://github.com/flutter/flutter.git -b stable
    echo "##vso[task.prependpath]`pwd`/flutter/bin"
    flutter --version
  displayName: "Instalar Flutter"

# 2. Restaurar dependências
- script: flutter pub get
  displayName: "Instalar dependências"

# 3. Build APK Release
- script: flutter build apk --release
  displayName: "Build APK Release"

# 4. Instalar Fastlane
- script: |
    sudo gem install fastlane -NV
    fastlane --version
  displayName: "Instalar Fastlane"

# 5. Upload para Google Play
- script: |
    cd android

    # O arquivo JSON precisa ser configurado no Azure DevOps (Secure Files)
    echo "Usando JSON: $(googlePlayJson.secureFilePath)"

    fastlane supply \
      --json_key "$(googlePlayJson.secureFilePath)" \
      --package_name "com.washingtonclimaco.task_manager_flutter" \
      --apk "../build/app/outputs/flutter-apk/app-release.apk" \
      --track production \
      --skip_upload_changelogs true
  displayName: "Enviar APK para Google Play"
  env:
    FASTLANE_DISABLE_COLORS: '1'
    SUPPLY_SKIP_UPLOAD_CHANGELOGS: '1'
  inputs:
    secureFile: google_play.json
