// Mocks generated by Mockito 5.4.4 from annotations
// in task_manager_flutter/test/screens/dashboard_financeiro_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i7;

import 'package:flutter/material.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:task_manager_flutter/models/conta_bancaria_model.dart' as _i5;
import 'package:task_manager_flutter/services/conta_bancaria_caller.dart'
    as _i4;
import 'package:task_manager_flutter/services/dashboard_financeiro_caller.dart'
    as _i2;
import 'package:task_manager_flutter/services/empresa_caller.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DashboardFinanceiroCaller].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardFinanceiroCaller extends _i1.Mock
    implements _i2.DashboardFinanceiroCaller {
  MockDashboardFinanceiroCaller() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> obterDashboard({
    int? empresaId,
    int? parceiroId,
    int? contaBancariaId,
    String? dataInicio,
    String? dataFim,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #obterDashboard,
          [],
          {
            #empresaId: empresaId,
            #parceiroId: parceiroId,
            #contaBancariaId: contaBancariaId,
            #dataInicio: dataInicio,
            #dataFim: dataFim,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> obterKpis({
    int? empresaId,
    int? parceiroId,
    int? dias,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #obterKpis,
          [],
          {
            #empresaId: empresaId,
            #parceiroId: parceiroId,
            #dias: dias,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<dynamic>> obterProjecao({
    int? empresaId,
    int? parceiroId,
    int? meses,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #obterProjecao,
          [],
          {
            #empresaId: empresaId,
            #parceiroId: parceiroId,
            #meses: meses,
          },
        ),
        returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i3.Future<List<dynamic>>);
}

/// A class which mocks [ContaBancariaCaller].
///
/// See the documentation for Mockito's code generation for more information.
class MockContaBancariaCaller extends _i1.Mock
    implements _i4.ContaBancariaCaller {
  MockContaBancariaCaller() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.ContaBancaria>> fetchContas(_i6.BuildContext? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchContas,
          [context],
        ),
        returnValue:
            _i3.Future<List<_i5.ContaBancaria>>.value(<_i5.ContaBancaria>[]),
      ) as _i3.Future<List<_i5.ContaBancaria>>);

  @override
  _i3.Future<bool> ativarConta(
    int? id,
    bool? ativo,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #ativarConta,
          [
            id,
            ativo,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> transferirSaldo({
    required int? contaOrigemId,
    required int? contaDestinoId,
    required double? valor,
    required int? empresaId,
    int? parceiroId,
    String? historico,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferirSaldo,
          [],
          {
            #contaOrigemId: contaOrigemId,
            #contaDestinoId: contaDestinoId,
            #valor: valor,
            #empresaId: empresaId,
            #parceiroId: parceiroId,
            #historico: historico,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i7.Uint8List?> gerarExtratoPdf({
    required int? contaId,
    required int? empresaId,
    int? parceiroId,
    required String? de,
    required String? ate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #gerarExtratoPdf,
          [],
          {
            #contaId: contaId,
            #empresaId: empresaId,
            #parceiroId: parceiroId,
            #de: de,
            #ate: ate,
          },
        ),
        returnValue: _i3.Future<_i7.Uint8List?>.value(),
      ) as _i3.Future<_i7.Uint8List?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> evolucaoSaldoDiario(
    int? contaId,
    int? days,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #evolucaoSaldoDiario,
          [
            contaId,
            days,
          ],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> listarSaldos({
    required int? empresaId,
    int? parceiroId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listarSaldos,
          [],
          {
            #empresaId: empresaId,
            #parceiroId: parceiroId,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [EmpresaCaller].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmpresaCaller extends _i1.Mock implements _i8.EmpresaCaller {
  MockEmpresaCaller() {
    _i1.throwOnMissingStub(this);
  }
}
